-- تشغيل هذا الكود في Supabase SQL Editor لإنشاء جدول الاشتراكات

CREATE TABLE IF NOT EXISTS public.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    plan_name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'active', -- active, pending, expired
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- إعطاء الصلاحيات للوصول إلى الجدول (RLS)
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to subscriptions" ON public.subscriptions FOR SELECT USING (true);
CREATE POLICY "Allow public insert access to subscriptions" ON public.subscriptions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access to subscriptions" ON public.subscriptions FOR UPDATE USING (true);

-- إضافة بعض البيانات التجريبية (Mock Data) لاختبار شكل الصفحة
INSERT INTO public.subscriptions (customer_name, phone, plan_name, price, status, start_date, end_date)
VALUES 
  ('أحمد محمود', '01011112222', 'باقة الصيانة الذهبية (سنة)', 1500, 'active', CURRENT_DATE, CURRENT_DATE + INTERVAL '1 year'),
  ('محمد غانم', '01234567890', 'صيانة دورية كل 3 شهور', 800, 'active', CURRENT_DATE - INTERVAL '1 month', CURRENT_DATE + INTERVAL '5 months'),
  ('سيد الشيتي', '01555554444', 'غسيل وتعقيم فوري', 300, 'pending', CURRENT_DATE, CURRENT_DATE + INTERVAL '1 day');
